import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// Конфигурация боковых панелей для 9D Methodology
const sidebars: SidebarsConfig = {
  // Основная боковая панель методологии
  methodologySidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Введение в 9D'
    },
    {
      type: 'category',
      label: 'Level 0: Business Readiness',
      items: [
        'level-0/overview',
        {
          type: 'category',
          label: 'Блоки оценки',
          items: [
            'level-0/blocks/economic-maturity',
            // Раскомментируйте после создания файлов:
            // 'level-0/blocks/marketing-maturity',
            // 'level-0/blocks/analytical-maturity',
            // 'level-0/blocks/leadership-maturity'
          ]
        },
        // Раскомментируйте после создания файла:
        // 'level-0/assessment-system'
      ]
    },
    {
      type: 'category',
      label: 'Level 1: D-Blocks',
      items: [
        'level-1/overview',
        {
          type: 'category',
          label: 'D1 DISCOVER',
          items: [
            'level-1/D1-discover/index',
            // Файл находится в другом месте:
            'd-blocks/d1-discover/jobs-to-be-done'
          ]
        },
        {
          type: 'category',
          label: 'D2 DEFINE',
          items: [
            'level-1/D2-define/index'
          ]
        },
        {
          type: 'category',
          label: 'D3 DESIGN',
          items: [
            'level-1/D3-design/index',
            'level-1/D3-design/product-strategy',
            'level-1/D3-design/ux-design',
            'level-1/D3-design/development',
            'level-1/D3-design/testing',
            'level-1/D3-design/integration'
          ]
        },
        {
          type: 'category',
          label: 'D4 DEVELOP',
          items: [
            'level-1/D4-develop/index'
          ]
        },
        {
          type: 'category',
          label: 'D5 DEPLOY',
          items: [
            'level-1/D5-deploy/index'
          ]
        },
        {
          type: 'category',
          label: 'D6 DELIVER',
          items: [
            'level-1/D6-deliver/index'
          ]
        },
        {
          type: 'category',
          label: 'D7 DATA',
          items: [
            'level-1/D7-data/index'
          ]
        },
        {
          type: 'category',
          label: 'D8 DECIDE',
          items: [
            'level-1/D8-decide/index'
          ]
        },
        {
          type: 'category',
          label: 'D9 DIRECT',
          items: [
            'level-1/D9-direct/index'
          ]
        }
      ]
    },
    /* Раскомментируйте после создания файлов:
    {
      type: 'category',
      label: 'Внедрение',
      items: [
        'implementation/case-studies',
        'implementation/templates',
        'implementation/tools'
      ]
    }
    */
  ],
  
  // Для обратной совместимости оставляем и tutorialSidebar
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}]
};

export default sidebars;
