import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// Конфигурация боковых панелей для 9D Methodology
const sidebars: SidebarsConfig = {
  // Основная боковая панель методологии
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Введение в 9D'
    },
    {
      type: 'category',
      label: 'Level 0: Business Readiness',
      items: [
        'level-0/overview',
        {
          type: 'category',
          label: 'Блоки оценки',
          items: [
            'level-0/blocks/economic-maturity',
            'level-0/blocks/marketing-maturity',
            'level-0/blocks/analytical-maturity',
            'level-0/blocks/leadership-maturity'
          ]
        },
        'level-0/assessment-system'
      ]
    },
    {
      type: 'category',
      label: 'Level 1: D-Blocks',
      items: [
        'level-1/overview',
        {
          type: 'category',
          label: 'D1 DISCOVER',
          items: [
            'level-1/D1-discover/index',
            'level-1/D1-discover/customer-research',
            'level-1/D1-discover/market-analysis',
            // Файл находится в другом месте:
            'd-blocks/d1-discover/jobs-to-be-done'
          ]
        },
        {
          type: 'category',
          label: 'D2 DEFINE',
          items: [
            'level-1/D2-define/index'
          ]
        },
        {
          type: 'category',
          label: 'D3 DESIGN',
          items: [
            'level-1/D3-design/index',
            'level-1/D3-design/product-strategy',
            'level-1/D3-design/ux-design',
            'level-1/D3-design/development',
            'level-1/D3-design/testing',
            'level-1/D3-design/integration'
          ]
        },
        {
          type: 'category',
          label: 'D4 DEVELOP',
          items: [
            'level-1/D4-develop/index',
            'level-1/D4-develop/development-mastery'
          ]
        },
        {
          type: 'category',
          label: 'D5 DEPLOY',
          items: [
            'level-1/D5-deploy/index',
            'level-1/D5-deploy/deployment-mastery',
            'level-1/D5-deploy/ecosystem-optimization'
          ]
        },
        {
          type: 'category',
          label: 'D6 DELIVER',
          items: [
            'level-1/D6-deliver/index',
            'level-1/D6-deliver/delivery-mastery'
          ]
        },
        {
          type: 'category',
          label: 'D7 DATA',
          items: [
            'level-1/D7-data/index'
          ]
        },
        {
          type: 'category',
          label: 'D8 DECIDE',
          items: [
            'level-1/D8-decide/index'
          ]
        },
        {
          type: 'category',
          label: 'D9 DIRECT',
          items: [
            'level-1/D9-direct/index'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Level 2: Methodology Validation',
      items: [
        'level-2/index',
        'level-2/methodological-foundation',
        'level-2/case1-saas-crypto',
        'level-2/case2-ecommerce-ai',
        'level-2/case3-fitness-app',
        'level-2/validation-scoring',
        'level-2/practical-tools',
        'level-2/case-studies',
        'level-2/summary'
      ]
    },
    {
      type: 'category',
      label: 'Внедрение',
      items: [
        'implementation/index',
        'implementation/strategy',
        'implementation/assessment',
        'implementation/planning',
        'implementation/tools',
        'implementation/case-studies',
        'implementation/templates'
      ]
    }
  ],
  
  // Боковая панель для автогенерации
  methodologySidebar: [{type: 'autogenerated', dirName: '.'}]
};

export default sidebars;
